# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: 1.0.0$(Rev:.r)  # Enables auto-incrementing version numbers like 1.0.01, 1.0.02, etc.

trigger:
- main

pool:
  name: Default  # Your self-hosted agent pool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'

steps:
# ✅ Install latest NuGet CLI
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

# ✅ Use specific .NET SDK version
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    version: $(dotNetVersion)

# ✅ Restore NuGet packages from feeds
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'

# ✅ Build the solution
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

# ✅ Run unit tests
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore'

# ✅ Pack the class library as a NuGet package with unique version
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringLibrary.csproj'
    versioningScheme: 'off'
    arguments: '--configuration $(buildConfiguration) /p:PackageVersion=$(Build.BuildNumber)'
    outputDir: '$(Build.ArtifactStagingDirectory)'

# ✅ Authenticate for Azure Artifacts feed access
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

# ✅ Push the NuGet package to Azure Artifacts
- task: NuGetCommand@2
  displayName: 'Push NuGet package to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'mrakib4'  # Replace with your actual feed name if different
    allowPackageConflicts: true

# ✅ Publish the package as a pipeline artifact (optional)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

